'use strict';

// The synthetic alert generator.
//
//   const { generateDataset } = require('./tools/synth/generate');
//   const dataset = generateDataset({ seed: 'noc-demo', count: 200 });
//
// Same seed and parameters produce a byte-identical dataset: nothing here
// reads the clock, the filesystem, or the environment. That is what makes the
// replay harness reproducible, and it is why no dataset is committed to the
// repository — the seed is the artefact, not the JSON.
//
// Everything produced is marked synthetic in three places: `synthetic: true`
// on each record, a marker line at the end of each alert text, and the
// dataset's own `meta.warning`. Resource names carry a `synth-` prefix on top
// of that, so the marking survives into the prompt and the rendered message.

const { parseDatadogAlert } = require('../../src/parseAlert');
const { makeRng } = require('./rng');
const { TEMPLATES, TYPES, markerLine } = require('./templates');
const V = require('./vocab');

// 2026-01-01T03:00:00Z. Fixed rather than `Date.now()` so a dataset generated
// today and one generated next year from the same seed are identical.
const DEFAULT_START = 1767236400000;

const WARNING =
  'SYNTHETIC DATA. Generated by noc-bot tools/synth. Every alert, resource ' +
  'name and value here is invented for testing this repository. None of it ' +
  'is captured, derived from, or representative of production traffic.';

const DEFAULTS = {
  seed: 'noc-demo',
  count: 200,
  windowMinutes: 120,
  startTime: DEFAULT_START,
  noiseRatio: 0.6,
  chatterRatio: 0.08,
  burstRatio: 0.25,
  burstSize: [2, 5],
  types: null,
};

const DUP_KINDS = ['exact_ts', 'exact_text', 'same_key'];

function clamp01(n, fallback) {
  const v = typeof n === 'number' && Number.isFinite(n) ? n : fallback;
  return Math.max(0, Math.min(1, v));
}

/**
 * Build a variant that keeps `state|alert_type|resource` identical but differs
 * inside the first 200 characters, so deduplication layer 3 catches it and
 * layers 1 and 2 do not. Returns null when the alert has no number early
 * enough to mutate — SYNTHETICS carries neither a value nor a threshold, and
 * the caller falls back to an `exact_text` duplicate for those.
 */
function sameKeyVariant(text, rng) {
  let out = null;

  const valueM = text.match(/^Value: ([\d.]+)$/m);
  if (valueM) {
    const decimals = (valueM[1].split('.')[1] || '').length;
    const bumped = parseFloat(valueM[1]) * (1 + rng.float(0.03, 0.18, 4));
    let v = decimals ? parseFloat(bumped.toFixed(decimals)) : Math.round(bumped);
    if (String(v) === valueM[1]) v = decimals ? parseFloat((v + 1 / Math.pow(10, decimals)).toFixed(decimals)) : v + 1;
    out = text.replace(/^Value: [\d.]+$/m, `Value: ${v}`);
  } else {
    // Pulsar carries a `subscription | backlog` table instead of a value line.
    const subM = text.match(/^(\S+) \| (\d+)$/m);
    if (subM) {
      const v = parseInt(subM[2], 10) + rng.int(1, 500);
      out = text.replace(/^\S+ \| \d+$/m, `${subM[1]} | ${v}`);
    }
  }

  // The mutation has to land inside the window layer 2 actually compares.
  // A long enough header could push it past 200 characters, in which case the
  // duplicate would be caught by the wrong layer and the dataset would quietly
  // stop testing what it claims to test.
  if (out && out.substring(0, 200) !== text.substring(0, 200)) return out;
  return null;
}

/** Pick a state and an over-threshold ratio from the record's intent. */
function shapeFromIntent(rng, intent) {
  if (intent === 'incident') {
    return {
      state: rng.chance(0.7) ? 'TRIGGERED' : 'RE-TRIGGERED',
      ratio: rng.float(1.5, 4, 3),
    };
  }
  // Noise is not one thing. A recovery is never answered at all; a WARN
  // barely over its threshold is what the classifier is allowed to silence;
  // and a TRIGGERED barely over its threshold is noise-shaped input that the
  // fail-safe cap explicitly refuses to silence. All three are generated.
  const roll = rng.next();
  if (roll < 0.35) return { state: 'RECOVERED', ratio: rng.float(0.2, 0.9, 3) };
  if (roll < 0.75) return { state: 'WARN', ratio: rng.float(1, 1.09, 3) };
  return { state: 'TRIGGERED', ratio: rng.float(1, 1.09, 3) };
}

function generateDataset(params) {
  const p = { ...DEFAULTS, ...(params || {}) };
  p.count = Math.max(1, Math.floor(p.count));
  p.windowMinutes = Math.max(1, p.windowMinutes);
  p.noiseRatio = clamp01(p.noiseRatio, DEFAULTS.noiseRatio);
  p.chatterRatio = clamp01(p.chatterRatio, DEFAULTS.chatterRatio);
  p.burstRatio = clamp01(p.burstRatio, DEFAULTS.burstRatio);

  const types = (p.types && p.types.length ? p.types : TYPES).slice();
  for (const t of types) {
    if (!TEMPLATES[t]) throw new Error(`unknown alert type for the generator: ${t}`);
  }

  const rng = makeRng(p.seed);
  const marker = markerLine(p.seed);
  const windowMs = p.windowMinutes * 60 * 1000;

  const staged = [];
  let seq = 0;
  let bursts = 0;

  for (let i = 0; i < p.count; i++) {
    const id = 'a' + String(i + 1).padStart(4, '0');
    const offsetMs = Math.floor(rng.next() * windowMs);

    if (rng.chance(p.chatterRatio)) {
      const rec = {
        offsetMs, seq: seq++,
        mensaje: rng.pick(V.CHATTER) + '\n\n' + marker,
        synthetic: true,
        synth: {
          id, intent: 'chatter', alert_type: null, state: null,
          resource: null, duplicate_of: null, duplicate_kind: null, burst_id: null,
        },
      };
      // A share of channel noise arrives as a join or an edit, which the
      // response gate rejects on `subtype` alone, before parsing matters.
      if (rng.chance(0.3)) rec.subtype = rng.chance(0.5) ? 'channel_join' : 'message_changed';
      staged.push(rec);
      continue;
    }

    const intent = rng.chance(p.noiseRatio) ? 'noise' : 'incident';
    const type = rng.pick(types);
    const { state, ratio } = shapeFromIntent(rng, intent);
    const ctx = {
      state, ratio,
      region: rng.pick(V.REGIONS),
      env: rng.pick(V.ENVS),
      backtick: rng.chance(0.3),
      runbook: rng.chance(0.5),
      url: rng.chance(0.4),
      monitorId: rng.int(10000000, 19999999),
    };
    const built = TEMPLATES[type](rng, ctx);
    const text = built.text + '\n\n' + marker;

    // The detection chain in src/parseAlert.js is ordered and matches on
    // substrings of the whole body, so a template can lose its own alert to an
    // earlier branch through any text it emits — a title, a tag, or a runbook
    // reference. Every record is parsed back before it is admitted, so a
    // dataset can never quietly claim to cover a type it does not.
    const roundTrip = parseDatadogAlert(text).alert_type;
    if (roundTrip !== built.alert_type) {
      throw new Error(
        `generator invariant broken: a ${built.alert_type} template produced text that ` +
        `parses as ${roundTrip}. The detection chain in src/parseAlert.js is ordered, so ` +
        'this template is emitting a substring an earlier branch claims.'
      );
    }

    const origin = {
      offsetMs, seq: seq++, mensaje: text, synthetic: true,
      synth: {
        id, intent, alert_type: built.alert_type, state,
        resource: built.resource, duplicate_of: null, duplicate_kind: null, burst_id: null,
      },
    };
    // A small share of otherwise well-formed alerts arrives edited in place,
    // which Slack marks with a subtype and the response gate refuses outright.
    // These have to be alerts rather than chatter to test anything: the gate
    // is an && chain evaluated in order, so a chatter message is already
    // rejected on its missing state before the subtype is ever considered.
    if (rng.chance(0.05)) origin.subtype = 'message_changed';
    staged.push(origin);

    if (!rng.chance(p.burstRatio)) continue;

    // A burst is the same condition delivered again within a couple of
    // minutes. The kinds cycle so all three within-run deduplication layers
    // get exercised rather than whichever one happens to fire first.
    const burstId = 'b' + String(++bursts).padStart(3, '0');
    origin.synth.burst_id = burstId;
    const repeats = rng.int(p.burstSize[0], p.burstSize[1]);

    for (let k = 0; k < repeats; k++) {
      let kind = DUP_KINDS[k % DUP_KINDS.length];
      let body = text;

      if (kind === 'same_key') {
        const variant = sameKeyVariant(built.text, rng);
        if (variant === null) kind = 'exact_text';
        else body = variant + '\n\n' + marker;
      }

      // A repeat lands seconds to minutes after the original, clamped to the
      // window so `windowMinutes` stays exact — the replay harness slices its
      // poll windows over precisely that range, and a burst tail hanging past
      // the end would fall outside every poll.
      const delta = rng.int(5, 150) * 1000;
      staged.push({
        offsetMs: kind === 'exact_ts' ? offsetMs : Math.min(offsetMs + delta, windowMs),
        seq: seq++,
        mensaje: body,
        synthetic: true,
        synth: {
          id: id + '-' + (k + 1), intent, alert_type: built.alert_type, state,
          resource: built.resource, duplicate_of: id, duplicate_kind: kind, burst_id: burstId,
        },
      });
    }
  }

  // Slack delivers in time order, so the dataset is ordered the same way. The
  // sort is stable on `seq`, which keeps a burst's origin ahead of its
  // duplicates when they share an offset.
  staged.sort((a, b) => (a.offsetMs - b.offsetMs) || (a.seq - b.seq));

  const tsById = {};
  let tsCounter = 0;
  const records = staged.map((r) => {
    let ts;
    if (r.synth.duplicate_kind === 'exact_ts' && tsById[r.synth.duplicate_of]) {
      ts = tsById[r.synth.duplicate_of];
    } else {
      const seconds = Math.floor((p.startTime + r.offsetMs) / 1000);
      ts = `${seconds}.${String(++tsCounter).padStart(6, '0')}`;
    }
    if (!r.synth.duplicate_of) tsById[r.synth.id] = ts;

    const out = { ts, mensaje: r.mensaje, synthetic: true, synth: r.synth };
    if (r.subtype) out.subtype = r.subtype;
    return out;
  });

  return { meta: buildMeta(p, types, records, bursts), records };
}

function tally(records, fn) {
  const out = {};
  for (const r of records) {
    const k = fn(r);
    if (k === null || k === undefined) continue;
    out[k] = (out[k] || 0) + 1;
  }
  return out;
}

function buildMeta(p, types, records, bursts) {
  return {
    synthetic: true,
    warning: WARNING,
    generator: 'noc-bot tools/synth',
    seed: p.seed,
    params: {
      count: p.count, windowMinutes: p.windowMinutes, startTime: p.startTime,
      noiseRatio: p.noiseRatio, chatterRatio: p.chatterRatio,
      burstRatio: p.burstRatio, burstSize: p.burstSize, types,
    },
    window: {
      start: new Date(p.startTime).toISOString(),
      end: new Date(p.startTime + p.windowMinutes * 60 * 1000).toISOString(),
      note: 'Simulated window. Timestamps are computed from startTime, not from the clock.',
    },
    counts: {
      records: records.length,
      bursts,
      by_intent: tally(records, (r) => r.synth.intent),
      by_type: tally(records, (r) => r.synth.alert_type),
      by_state: tally(records, (r) => r.synth.state),
      by_duplicate_kind: tally(records, (r) => r.synth.duplicate_kind),
      with_subtype: records.filter((r) => r.subtype).length,
    },
  };
}

module.exports = { generateDataset, DEFAULTS, DEFAULT_START, WARNING, TYPES };
