'use strict';

// One alert-text template per alert type the parser can actually emit.
//
// `parseDatadogAlert` detects the type with an ORDERED chain of substring
// tests, first match wins, so these templates are not independent of each
// other: a template must avoid every substring that an EARLIER branch keys on,
// or its alert is silently reclassified. The chain order, from
// src/parseAlert.js, is:
//
//   SYNTHETICS, LAMBDA_ERROR, AUTH0_TOKEN, SQS_DLQ, ALB_RESPONSE_TIME,
//   RDS_CONNECTIONS, RDS_BLOCKING, PULSAR_BACKLOG, APIGW_4XX,
//   ECS_CPU, ECS_MEMORY, ECS_GENERIC
//
// Each template below notes what it has to stay clear of. The constraints are
// not decorative — e.g. an RDS_BLOCKING alert carrying a `database_instance:`
// tag is claimed by RDS_CONNECTIONS, and an ECS alert mentioning "backlog" is
// claimed by PULSAR_BACKLOG. test/generate.test.js asserts that every
// generated record parses back to the type the generator intended, so a
// regression here fails CI rather than quietly skewing the dataset.

const { ALERT_TYPE_TO_RUNBOOK, KNOWN_RUNBOOKS } = require('../../src/runbooks');
const V = require('./vocab');

// The runbook reference line participates in type detection, because the
// detection chain tests substrings against the whole alert body and the
// reference carries the catalog title. ECS_GENERIC maps to RUNBOOK-001, whose
// title is "High CPU en servicio ECS", so printing that title inside an
// ECS_GENERIC alert makes the `high cpu` test match and the alert is parsed as
// ECS_CPU instead. The reference is emitted without its title for those types;
// the parser fills `runbook_name` in from KNOWN_RUNBOOKS either way, so
// nothing downstream loses information.
//
// This is a property of src/parseAlert.js, not of the generator. It is left
// alone here rather than worked around in src/, which stays byte-identical to
// the workflow export.
const RUNBOOK_TITLE_RECLASSIFIES = new Set(['ECS_GENERIC']);

const STATE_PREFIX = {
  'TRIGGERED': '[Triggered]',
  'RE-TRIGGERED': '[Re-Triggered]',
  'WARN': '[Warn]',
  'RECOVERED': '[Recovered]',
};

/** The marker every generated alert text carries, as its last line. */
function markerLine(seed) {
  return `[SYNTHETIC DATA - generated by noc-bot tools/synth, seed=${seed}. Not a real alert.]`;
}

/** Matches the marker so tests can strip it and re-parse without it. */
const MARKER_RE = /\n*\[SYNTHETIC DATA - [^\]]*\]\s*$/;

/**
 * Assemble the standard Datadog-in-Slack layout the parser expects: a state in
 * the first line, a query line, value and threshold, a tag block, and an
 * optional runbook reference and monitor link.
 */
function layout(o) {
  const lines = [`${STATE_PREFIX[o.state]} ${o.title}`];

  if (o.query) {
    // A backticked query is what populates `dd_query`, which makes
    // buildDDQuery use the alert's own query instead of its per-type table.
    // Only the expression is quoted; the comparison stays outside so the
    // threshold regex still finds it.
    lines.push(o.backtick ? '`' + o.query + '`' + ` > ${o.threshold}` : `${o.query} > ${o.threshold}`);
  }

  if (o.value !== null && o.value !== undefined) {
    lines.push('', `Value: ${o.value}`, `Threshold: > ${o.threshold}`);
  } else if (o.threshold !== null && o.threshold !== undefined) {
    lines.push('', `Threshold: > ${o.threshold}`);
  }

  for (const block of o.blocks || []) lines.push('', block);

  lines.push('', 'Tags', ...o.tags);

  if (o.runbook) {
    const id = ALERT_TYPE_TO_RUNBOOK[o.type];
    if (id) {
      const title = RUNBOOK_TITLE_RECLASSIFIES.has(o.type)
        ? '' : ` ${KNOWN_RUNBOOKS[id] || 'Ver runbook'}`;
      lines.push('', `${id}:${title}`);
    }
  }
  if (o.url) lines.push(`https://app.datadoghq.com/monitors/${o.monitorId}`);

  return lines.join('\n');
}

/** Scale a threshold by the intent ratio, clamped and rounded per metric kind. */
function scaled(threshold, ratio, decimals, max) {
  let v = threshold * ratio;
  if (max !== undefined) v = Math.min(v, max);
  return decimals === 0 ? Math.max(0, Math.round(v)) : parseFloat(v.toFixed(decimals));
}

// ─────────────────────────────────────────────────────────────────────────
// Templates. Each returns { text, alert_type, resource, threshold, metric_value }.
// `ctx` carries state, ratio, backtick, runbook, url and monitorId.
// ─────────────────────────────────────────────────────────────────────────

const TEMPLATES = {
  // Percentage metric: the value is clamped to 99.9, so a monitor with a high
  // threshold cannot produce a large over-threshold ratio. That is a real
  // property of percentage alerts and is left in rather than engineered away.
  ECS_CPU(rng, ctx) {
    const svc = rng.pick(V.SERVICES);
    const threshold = rng.pick([60, 70, 75, 80, 85, 90]);
    return {
      alert_type: 'ECS_CPU', resource: svc, threshold,
      metric_value: scaled(threshold, ctx.ratio, 1, 99.9),
      text: layout({
        ...ctx, type: 'ECS_CPU', title: 'High CPU on ECS service', threshold,
        value: scaled(threshold, ctx.ratio, 1, 99.9),
        query: `avg(last_15m):avg:aws.ecs.cpuutilization{servicename:${svc}}`,
        tags: [`servicename:${svc}`, `cluster:${rng.pick(V.CLUSTERS)}`, `region: ${ctx.region}`, `env:${ctx.env}`],
      }),
    };
  },

  // Must avoid "high cpu" and "ecs.cpu" — ECS_CPU is tested first.
  ECS_MEMORY(rng, ctx) {
    const svc = rng.pick(V.SERVICES);
    const threshold = rng.pick([70, 80, 85, 90]);
    return {
      alert_type: 'ECS_MEMORY', resource: svc, threshold,
      metric_value: scaled(threshold, ctx.ratio, 1, 99.9),
      text: layout({
        ...ctx, type: 'ECS_MEMORY', title: 'High Memory on ECS service', threshold,
        value: scaled(threshold, ctx.ratio, 1, 99.9),
        query: `avg(last_15m):avg:aws.ecs.memory_utilization{servicename:${svc}}`,
        tags: [`servicename:${svc}`, `cluster:${rng.pick(V.CLUSTERS)}`, `region: ${ctx.region}`, `env:${ctx.env}`],
      }),
    };
  },

  // The catch-all ECS branch: needs `servicename:` but must mention neither
  // cpu nor memory, and must not say "backlog" (PULSAR_BACKLOG is earlier).
  ECS_GENERIC(rng, ctx) {
    const svc = rng.pick(V.SERVICES);
    const threshold = rng.pick([5, 10, 20]);
    return {
      alert_type: 'ECS_GENERIC', resource: svc, threshold,
      metric_value: scaled(threshold, ctx.ratio, 0),
      text: layout({
        ...ctx, type: 'ECS_GENERIC', title: 'ECS service task restarts', threshold,
        value: scaled(threshold, ctx.ratio, 0),
        query: `sum(last_15m):sum:aws.ecs.service.task_restarts{servicename:${svc}}`,
        tags: [`servicename:${svc}`, `cluster:${rng.pick(V.CLUSTERS)}`, `region: ${ctx.region}`, `env:${ctx.env}`],
      }),
    };
  },

  LAMBDA_ERROR(rng, ctx) {
    const fn = rng.pick(V.FUNCTIONS);
    const threshold = rng.pick([5, 10, 25, 50]);
    return {
      alert_type: 'LAMBDA_ERROR', resource: fn, threshold,
      metric_value: scaled(threshold, ctx.ratio, 0),
      text: layout({
        ...ctx, type: 'LAMBDA_ERROR', title: 'Lambda Errors', threshold,
        value: scaled(threshold, ctx.ratio, 0),
        query: `sum(last_5m):sum:aws.lambda.errors{functionname:${fn}}.as_count()`,
        tags: [`functionname:${fn}`, `region: ${ctx.region}`, `env:${ctx.env}`],
      }),
    };
  },

  // A `> 0` threshold is common for DLQ monitors and disables the classifier's
  // ratio signal entirely, since it guards on `threshold > 0`. Generated
  // sometimes on purpose so that path is exercised.
  SQS_DLQ(rng, ctx) {
    const q = rng.pick(V.QUEUES);
    const zeroThreshold = rng.chance(0.4);
    const threshold = zeroThreshold ? 0 : rng.pick([50, 100, 250]);
    const value = zeroThreshold ? rng.int(5, 800) : scaled(threshold, ctx.ratio, 0);
    return {
      alert_type: 'SQS_DLQ', resource: q, threshold, metric_value: value,
      text: layout({
        ...ctx, type: 'SQS_DLQ', title: 'Messages available on SQS DLQ', threshold, value,
        query: `avg(last_5m):avg:aws.sqs.approximate_number_of_messages_visible{queuename:${q}}`,
        tags: [`queuename:${q}`, `region: ${ctx.region}`, `env:${ctx.env}`],
      }),
    };
  },

  RDS_CONNECTIONS(rng, ctx) {
    const db = rng.pick(V.DATABASES);
    const threshold = rng.pick([400, 600, 800, 1000]);
    return {
      alert_type: 'RDS_CONNECTIONS', resource: db, threshold,
      metric_value: scaled(threshold, ctx.ratio, 0),
      text: layout({
        ...ctx, type: 'RDS_CONNECTIONS', title: 'RDS High Connections', threshold,
        value: scaled(threshold, ctx.ratio, 0),
        query: `avg(last_10m):avg:aws.rds.database_connections{database_instance:${db}}`,
        tags: [`database_instance:${db}`, `region: ${ctx.region}`, `env:${ctx.env}`],
      }),
    };
  },

  // Detected from "blocking" plus a `Host:` line. Deliberately carries NO
  // `database_instance:` tag: RDS_CONNECTIONS is tested first and would claim
  // it. The resource comes off the query line's `host:` either way.
  RDS_BLOCKING(rng, ctx) {
    const host = rng.pick(V.DB_HOSTS);
    const threshold = rng.pick([3, 5, 10]);
    return {
      alert_type: 'RDS_BLOCKING', resource: host, threshold,
      metric_value: scaled(threshold, ctx.ratio, 0),
      text: layout({
        ...ctx, type: 'RDS_BLOCKING', title: 'RDS blocking sessions detected', threshold,
        value: scaled(threshold, ctx.ratio, 0),
        query: `avg(last_10m):avg:aws.rds.blocking_sessions{host:${host}}`,
        tags: [`Host: ${host}`, `region: ${ctx.region}`, `env:${ctx.env}`],
      }),
    };
  },

  ALB_RESPONSE_TIME(rng, ctx) {
    const lb = rng.pick(V.LOAD_BALANCERS);
    const threshold = rng.pick([1, 2, 3]);
    return {
      alert_type: 'ALB_RESPONSE_TIME', resource: lb, threshold,
      metric_value: scaled(threshold, ctx.ratio, 2),
      text: layout({
        ...ctx, type: 'ALB_RESPONSE_TIME', title: 'ALB target response time high', threshold,
        value: scaled(threshold, ctx.ratio, 2),
        query: `avg(last_10m):avg:aws.applicationelb.target_response_time.average{loadbalancer:${lb}}`,
        tags: [`loadbalancer:${lb}`, `region: ${ctx.region}`, `env:${ctx.env}`],
      }),
    };
  },

  APIGW_4XX(rng, ctx) {
    const api = rng.pick(V.APIS);
    const threshold = rng.pick([25, 50, 100]);
    return {
      alert_type: 'APIGW_4XX', resource: api, threshold,
      metric_value: scaled(threshold, ctx.ratio, 0),
      text: layout({
        ...ctx, type: 'APIGW_4XX', title: 'API Gateway 4XX errors', threshold,
        value: scaled(threshold, ctx.ratio, 0),
        query: `sum(last_5m):sum:aws.apigateway.4xxerror{apiname:${api}}`,
        tags: [`apiname:${api}`, `region: ${ctx.region}`, `env:${ctx.env}`],
      }),
    };
  },

  // The parser hardcodes resource = 'auth0' for this type, so the connection
  // name below never reaches the pipeline. Every AUTH0_TOKEN alert therefore
  // shares one deduplication key per state — which is why they collapse hard
  // in layer 3. That is the real behaviour, not a generator artefact.
  AUTH0_TOKEN(rng, ctx) {
    const conn = rng.pick(V.AUTH_CONNECTIONS);
    const threshold = rng.pick([10, 25, 50]);
    return {
      alert_type: 'AUTH0_TOKEN', resource: 'auth0', threshold,
      metric_value: scaled(threshold, ctx.ratio, 0),
      text: layout({
        ...ctx, type: 'AUTH0_TOKEN', title: 'Auth0 token endpoint failure rate', threshold,
        value: scaled(threshold, ctx.ratio, 0),
        query: `sum(last_5m):sum:auth0.token_errors{connection:${conn}}`,
        tags: [`connection:${conn}`, `region: ${ctx.region}`, `env:${ctx.env}`],
      }),
    };
  },

  // The parser reads a `name | value` table here and overrides metric_value
  // with the maximum, so no `Value:` line is emitted. Must avoid "high cpu",
  // "high memory", "memory_utilization" and "ecs cluster", which all disable
  // this branch, and must not carry a queue tag (SQS_DLQ is earlier).
  PULSAR_BACKLOG(rng, ctx) {
    const topic = rng.pick(V.TOPICS);
    const threshold = rng.pick([1000, 5000, 20000]);
    const subs = [];
    const used = new Set();
    const n = rng.int(2, 3);
    for (let i = 0; i < n; i++) {
      let s = rng.pick(V.SUBSCRIPTIONS);
      let guard = 0;
      while (used.has(s) && guard++ < 10) s = rng.pick(V.SUBSCRIPTIONS);
      used.add(s);
      subs.push({ name: s, value: scaled(threshold, ctx.ratio * (1 - i * 0.3), 0) });
    }
    const block = 'Subscriptions\n' + subs.map((s) => `${s.name} | ${s.value}`).join('\n');
    return {
      alert_type: 'PULSAR_BACKLOG', resource: subs[0].name, threshold,
      metric_value: Math.max(...subs.map((s) => s.value)),
      text: layout({
        ...ctx, type: 'PULSAR_BACKLOG', title: 'Pulsar subscription backlog growing',
        threshold, value: null, blocks: [block],
        query: `avg(last_10m):avg:pulsar.subscription.msg_backlog{topic:${topic}}`,
        tags: [`topic:${topic}`, `region: ${ctx.region}`, `env:${ctx.env}`],
      }),
    };
  },

  // No metric and no threshold, which is how a synthetics failure actually
  // arrives; the classifier's ratio signal is skipped for these. The resource
  // is pulled out of prose by `The service X is down`, not from a tag.
  SYNTHETICS(rng, ctx) {
    const mon = rng.pick(V.WEB_MONITORS);
    return {
      alert_type: 'SYNTHETICS', resource: mon, threshold: null, metric_value: null,
      text: layout({
        ...ctx, type: 'SYNTHETICS', title: 'Synthetics monitor failure',
        threshold: null, value: null,
        query: null,
        blocks: ['monitor-type:synthetic', `The service ${mon} is down`],
        tags: [`region: ${ctx.region}`, `env:${ctx.env}`],
      }),
    };
  },
};

/** The types this generator can produce, in chain order. */
const TYPES = Object.keys(TEMPLATES);

module.exports = {
  TEMPLATES, TYPES, STATE_PREFIX, markerLine, MARKER_RE,
  RUNBOOK_TITLE_RECLASSIFIES,
};
